# Generated by Django 3.1.2 on 2020-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phonecode', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
