# Generated by Django 3.1.2 on 2020-10-29 14:36

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_EN', models.CharField(max_length=255)),
                ('title_AR', models.CharField(max_length=255)),
                ('is_delete', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='Specilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_EN', models.CharField(max_length=255)),
                ('title_AR', models.CharField(default='', max_length=255)),
                ('is_delete', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Specilization',
            },
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='description',
            new_name='description_AR',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='title',
            new_name='title_AR',
        ),
        migrations.AddField(
            model_name='updates',
            name='description_EN',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='title_EN',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
